### ISSUE TITLE
Customisable hotkeys

### ISSUE THREAD

**Issue by Harjot1Singh** [ShabadOS/presenter#176]
Though the above hotkey suggestions are not in place and we could implement them on a global level, I think most users would still be confused why cmd+c doesn't work, since that's basically the universal hotkey for copy everywhere else.

So regardless of the suggestions, a cmd+c/three-vertical-dot/right-click menu should be present for those users. This is just one more keypress in the above example. For example instead of CMD+G it would be CMD+C and then G on it's own.

For @preetcharan specific use-case we can either add direct hotkeys for the functions, since we do not use those hotkeys yet. Then if we need to use them for something else, perhaps we can revisit.

Or, ideally, the user should be allowed to set their own hotkeys for functions. We could have a list of "un-hotkeyed" functions at the bottom of the list that the user can supply their own hotkeys for. Or we could even set the hotkey for copy gurbani as CMD+C, G and users like @preetcharan could overwrite that with simply CMD+G.

_Originally posted by @bhajneet in https://github.com/ShabadOS/desktop/issues/103#issuecomment-507256944_

**Comment by bhajneet** [comment]
Need to be able to do combos, normal press, long press
