### ISSUE TITLE
Implement non-deletable hotkeys and addable hotkeys for certain hotkey functions

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/presenter#426]
These two hotkeys should never be removable, but there could be extra hotkeys added for it.

_Originally posted by @bhajneet in https://github.com/ShabadOS/desktop/issues/425#issuecomment-589661538_

**Comment by Harjot1Singh** [comment]
any others?

**Comment by bhajneet** [comment]
Probably arrow keys (though j and l can be removed I suppose)

I would think anything that is super core to the concept of using shabad os should not be configurable. Arrows, enter, hide controller, full screen. Maybe activities as well? /, y, b, g. I would think it odd if someone changed the esc key for clearing as well. These should remain "core" hotkeys that anyone who needs to use shabad os elsewhere can use.

What do you think?

**Comment by Harjot1Singh** [comment]
I actually think that all hotkeys should be all be reassignable. You may wish to change the activate line hotkey to `.`, and I see nothing wrong with that. 

The only ones that I think should be fixed are arrow up and down + enter in the controller, and that’s it, because they’re not really hotkeys

**Comment by bhajneet** [comment]
I just don't want to go to a different gurdwara and not be able to use basic hotkeys. So whatever you want to define as basic hotkeys needed for the most basic functioning of shabad os with the controller hidden on a single-presentation display will work for me. I think those are ctrl+h, arrows, enter, esc, spacebar, and number 1 key/home key.

**Comment by bhajneet** [comment]
This doesn't mean they can't add a hotkey "." to activate the line. It's not being used for any of the basic hotkeys so you can add that on to the enter hotkey.
