### ISSUE TITLE
Explore folder/lists for bookmarks

### ISSUE THREAD

**Issue by bhajneet** [shabados/presenter#483]
List out what bookmarks we want for desktop/mobile

**Comment by bhajneet** [comment]
My proposal is for "lists". There would be no bookmarks in the default / root level. There would only be names of "lists" in the default / root level. These "lists" act the same as a single-depth folder.

## 1. Lists Proposal

Pros:

- Shabads can be added to multiple lists very easily
- Shabads can be found in no more than one jump
- Editing a bookmark's location(s) is easier
- Sharing lists with other users is easier than sharing a nested folder (a list just goes in the flat list of lists, a folder has to be chosen where it gets put) an extension of "sharing" becomes "broadcasting" so people could subscribe to an online list more easily

Cons:

- May require more scrolling for the user
- May require more dragging of list ordering for better organization
- Does not "organize" well for variations of the same concept (nitnem for different schools of thought)

**Example tree:** // First nine cannot be re-arranged

- **Saved For Later** // Default list for user bookmarks to go in
- **Nitnem (Taksal)** // These may use different sources for compositional banis or include different lengths
  - Jap Ji Sahib
  - Jaap Sahib
  - ...
- **Nitnem (SGPC)** // These maybe follow SGPC published nitnem gutke
  - Jap Ji Sahib
  - Jaap Sahib
  - ...
- **Asa Di Vaar** // Note both the bani for the entire and each individual is available
  - Full 24 Chhakke
  - Chhakka 1
  - Chhakka 2
  - ...
- **Sundar Gutka** // These would contain nitnem, asa di vaar, and more -- repeating is allowed
- **Anand Karaj** // Shabads related to marriage ceremony including 4 laavan
- **Final rites**
- **Hukamnama** // Could be an optional list that requires subscribing to - List of different gurdwara hukams from around the world that are automatically updated and includes any number of user hukamnama options that are automatically chosen each day
- **Paath** // List of different paath readings of compositions. Perhaps multiple people use the same tablet for sehaj paath of Sri Guru Granth Sahib ji, they can have them all in this Paath list
- **User list 1** // perhaps for keertan program
- **User list 2** // perhaps for thematic
- **User list 3** // perhaps for presentation/katha/speech purposes
- **Subscribed BoS** // perhaps a list of shabads for basics of sikhi's most recent video, can be cleared and added to again for each new video and shows "last updated" date as well as "home page" of subscribed list which points to the video
- ...

## 2. Tree Proposal

Pros:

- A lot more organization customization / capability (for advanced users willing to spend the time and effort)
- Potentially less visual "clutter" to scroll through

Cons:

- Can create annoying navigation situations (If we allow a default location of save to be where you last saved, and that is a nested folder, the user must "edit" location by first leaving to root folder, then delving into a different structure/nest to save it in the correct place)
- Seeing where a bookmark is saved is harder to do (In a single flat list, you can see where the bookmark is saved in the same scrolling view)
- Sharing of nested folders is harder conceptually on the end user (imo). Similarly, organizing of nested folders is more work for any user even for themselves. Sometimes have to stop the user from being too smart for their own good ? 😄 

## 3. Hybrid Proposal

Root folder contains non-customizable base folders. Shabad OS folders can contain folders within folders perhaps. User folder can only contain lists and can be located in their own "User folder" or simply as lists below the Shabad OS folders.

Pros:

- Allows for less visual information without sacrificing simplicity of user bookmarking
- Cuts down scrolling, at the cost of one extra folder depth requirement from bookmark root
- Shabad OS folders are easier to organize, though at the cost of requiring extra work from the user

Cons:

- Still doesn't allow power users to create lists within lists for their custom bookmarks (No folder for "keertan set lists", or "presentations")
- Shabad OS folders could also be annoying to traverse if there is too much depth.

- **<username>'s Bookmarks** // Either this is it's own folder at the top of the root folder, or it's children are listed alongside (and below) the root Shabad OS folders
  - Saved for later // where a default user bookmark goes for later sorting, cannot be moved/re-arranged
  - User list 1 // perhaps for keertan program
  - User list 2 // perhaps for thematic
  - User list 3 // perhaps for presentation/katha/speech purposes
  - Custom Nitnem/Sundar Gutka // perhaps user wishes to do nitnem with a superset not available
- **Nitnem**
  - Nitnem (Taksal)
  - Nitnem (SGPC)
  - ...
- **Sundar Gutka**
- etc.

## Conclusion

Personally my goals for our bookmarking is twofold: (1) to include commonly read bani/shabads in a well organized and easily accessible way, and (2) easy user bookmarking for future reference (usually one "parent" name is all that's required)

* If we keep things to a single list format we will avoid more than three taps to get anywhere (1: Bookmarks > 2: List > 3: Item).
* If we keep things in a single list format, consumption of pre-defined bookmark lists is easier (they don't have to navigate around to see where what is)
* We glean more easily where a shabad is saved (when editing a bookmark / it's locations, you see one flat list with a check mark next to the list name indicating it's saved in there).
* We also allow for more customization of the bookmark itself without adding on the worry of where it is (choose whether the bookmark is opened in reader mode by default, which source to use for the bookmark, whether to make it a "broadcast" bookmark for other users to subscribe to like a hukamnama, etc.).
* Better navigation of lots of bookmarks requires a search bookmarks feature regardless of folder structure, and I will argue that remembering the names of your lists is easier when it's in one flat list that is viewed when scrolling
* Lists are easier than folders within folders for users to conceptually understand creating, managing, editing, etc.
* Users may not find the "look" of multiple lists in scroll view appealing, but they should find it easier / simpler (and smart ones could avoid by searching the list name or sorting by date, etc.). Sorting is easier when you are sorting a flat level of lists as opposed to nested folders.

**Comment by saihaj** [comment]
I agree because the main purpose is that one can access something quickly.
> If we keep things to a single list format we will avoid more than three taps to get anywhere (1: Bookmarks > 2: List > 3: Item).

With _Hybrid_ we are trying to put in _List_ and _Tree_ together so it should allow users: 
>Still doesn't allow power users to create lists within lists for their custom bookmarks (No folder for "keertan set lists", or "presentations")

Question: User can modify the predefined bookmarks?

**Comment by bhajneet** [comment]
Users should not be able to modify predefined bookmarks (in hybrid these would be the "folders" bookmarks)

User should be able to "hide" the default predefined bookmarks. Though how the user will "unhide" them is a good question.

Hybrid would not allow users to customize lists within lists. Hybrid allows users to have their lists in a flat level and includes predefined folders from Shabad OS to cut down on clutter perhaps. Hybrid then allows either the lists to be in the root directory or in it's own folder "User's Bookmarks".

Personally I don't see the benefit of Hybrid aside from a very shallow level of organization for predefined bookmarks. Especially if user can hide the extra predefined lists in prop 1, it should not be considered too much of a clutter.

**Comment by bhajneet** [comment]
I would also say I'd rather see hiding/archiving of lists rather than folders. This would allow there to be "current lists" and "inactive lists" which can still be accessed though not cluttering the main bookmarks page.

**Comment by bhajneet** [comment]
This was more a mobile issue and has been resolved. Can be linked for information.

End choice is a list of only folders. Each folder has a list of only bookmarks. Folders are renamed "Collections". Items are still named "Bookmarks".
