### ISSUE TITLE
(Search): fix font styling 

### ISSUE THREAD

**Issue by saihaj** [shabados/presenter#526]
![image](https://user-images.githubusercontent.com/14130567/81875218-ce09f180-954d-11ea-93a8-e464c7f31798.png)

Font weights:
* Punjabi too heavy
* Translit not making matching heavier than non-matching as gurmukhi does

---

![image](https://user-images.githubusercontent.com/14130567/81875331-0c071580-954e-11ea-9281-0a491e114575.png)

Line heights:
* Urdu not tall enough

_Originally posted by @bhajneet in https://github.com/ShabadOS/desktop/pull/510#issuecomment-628293980_

**Comment by saihaj** [comment]
> Use this font for now.
<sub>[View in Slack](https://shabados.slack.com/archives/CT3RUB71A/p1589557850005900)</sub>

**Comment by saihaj** [comment]
> for urdu, that is how the script works. dunno what other explanation to give. unlike like the naksh script used in arabic countries, nastaliq grows in height depending on the length of the word
<sub>[View in Slack](https://shabados.slack.com/archives/CT3RUB71A/p1589557748005500)</sub>

**Comment by bhajneet** [comment]
Open Anmol Uni is deprecated as of v2.5.0 of gurbani now fonts. 

The Open Satluj Uni font which replaced it does not have the same styling as Open Gurbani Akhar.

The 2.4.0 Open Anmol Uni font only contains a bold weight.

So I cannot fix this by adding deprecated 2.4.0 regular font weight. And I'm not sure I want to resolve this with differing style of gurmukhi fonts for gurbani and punjabi via the 2.5.2 Open Satluj Uni font.

**Comment by bhajneet** [comment]
Since the font is deprecated and no longer in development, we would need to switch our fonts around.

New fonts would have to look the same in ascii/unicode (as they do now), but also come in multiple weights.

Our unicode font does not have a "regular" font weight apparently. Since it's no longer in development, the only other option is to look at choosing new fonts

**Comment by Sarabveer** [comment]
I have uploaded a regular font that can be used in Slack.

A new `OpenGurbaniUni` font is in development, but until then the older fonts should suffice.

**Comment by saihaj** [comment]
@bhajneet is this resolved?

**Comment by bhajneet** [comment]
If you find it's not resolved, re-open with concrete steps to resolution, else leave closed.
