### ISSUE TITLE
Broken search results highlighter for matching hindi/urdu translits

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/presenter#567]
**Screenshots**
![image](https://user-images.githubusercontent.com/14130567/83332983-4ec62e80-a26c-11ea-9bdc-2e1f34c661ef.png)

![image](https://user-images.githubusercontent.com/14130567/83332993-5554a600-a26c-11ea-9921-fa4fdfa23b22.png)

![image](https://user-images.githubusercontent.com/14130567/83332997-5a195a00-a26c-11ea-8969-0cc5dcb4ac6a.png)

**Additional context**
Inspecting does show that some "matched" span is added, without any text.

**Comment by saihaj** [comment]
English translit too. Also why last word is repeated twice in translits?
<img width="489" alt="image" src="https://user-images.githubusercontent.com/44710980/83334507-a19fe600-a26c-11ea-824d-1af683f4f099.png">
