### ISSUE TITLE
Last word repeating in search results

### ISSUE THREAD

**Issue by saihaj** [ShabadOS/presenter#569]
**Describe the bug**
When transliterations are turned on for search results. Last word is repeated twice.

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Activities' > 'Search'
3. Select 'English' in 'Transliterations'
4. Go back to controller and search 'qq'
5. See the last word is repeated for everything

**Screenshots**
<img width="1678" alt="image" src="https://user-images.githubusercontent.com/44710980/83334749-47a02000-a26e-11ea-8228-d08c42e119d6.png">

**Specs**
 - Version: Dev branch head at 0a990ac

**Comment by Sarabveer** [comment]
Aren't the transliterations being fetched from the DB? Are they being done on the fly?

**Comment by saihaj** [comment]
> Aren't the transliterations being fetched from the DB?
DB has correct something done wrong on frontend.

> Are they being done on the fly?
Yes

**Comment by saihaj** [comment]
#567 Related to this since matching translit has issues.
<img width="289" alt="image" src="https://user-images.githubusercontent.com/44710980/83335988-0a3f9080-a276-11ea-8884-200dea162477.png">

**Comment by saihaj** [comment]
<img width="471" alt="image" src="https://user-images.githubusercontent.com/44710980/84937798-ed8ebf80-b0a1-11ea-943d-1b9d0ef50233.png">
