### ISSUE TITLE
frontend: update React v17 and CRA v4

### ISSUE THREAD

**Issue by saihaj** [shabados/presenter#612]
Checkout React v17 [blog post](https://reactjs.org/blog/2020/10/20/react-v17.html) and CRA v4 [release](https://github.com/facebook/create-react-app/releases/tag/v4.0.0) for breaking changes

**Comment by bhajneet** [comment]
@saihaj also this one I think was related to recent PRs

**Comment by saihaj** [comment]
This still needs to be done
