### ISSUE TITLE
Update electron

### ISSUE THREAD

**Issue by saihaj** [shabados/presenter#613]
According to [release notes `v7.3.3`](https://github.com/electron/electron/releases/tag/v7.3.3) 
> Electron 7.x.y has reached end-of-support as per the project's [support policy](https://www.electronjs.org/docs/tutorial/support#supported-versions). Developers and applications are encouraged to upgrade to a newer version of Electron.

Do we update to the latest version i.e. [`v10.x`](https://www.electronjs.org/releases/stable#10.1.5) that will probably be supported for next few years of do we just make one major bump i.e. `v.7.x.y` -> `v.8.x.y`?

**Comment by bhajneet** [comment]
@saihaj please update

**Comment by saihaj** [comment]
https://github.com/shabados/presenter/pull/652
