### ISSUE TITLE
incompatible babel-eslint versions causing frontend to crash

### ISSUE THREAD

**Issue by bhajneet** [shabados/presenter#614]
**Describe the bug**

**To Reproduce**
1. Checkout PR #586
2. `npm i`
3. `npm start`

**Screenshots**
![image](https://user-images.githubusercontent.com/14130567/97469803-2fb3f180-191d-11eb-8ee2-5a1d3ea0c9e1.png)

@Harjot1Singh please tell me what you want me to do to fix this

**Comment by saihaj** [comment]
Can you try merging current dev in that branch because that branch is outdated and I fixed this in #605

**Comment by bhajneet** [comment]
That is what I did

Should I try deleting node_modules, package-lock.json etc? I'd really rather avoid all that again lol

**Comment by saihaj** [comment]
> Should I try deleting node_modules, package-lock.json etc?

yes please  : )

**Comment by bhajneet** [comment]
deleting node_modules and package-lock.json files did not work

uninstalling babel-eslint and re-installing it brings it up to correct version

going to commit the new package.json and package-locks
