### ISSUE TITLE
Hotkey for going to next or previous shabad

### ISSUE THREAD

**Issue by readgurbani** [shabados/presenter#645]
Sometimes kirtan require to display next shabad after the last line. In this case, the user had to press the arrow buttons to go to next shabad.

It will be nice to have hotkey to navigate to next or previous shabad.

Recommended shortcuts:
alt + [page down / right arrow] for next shabad
alt + [page up / left arrow] for previous shabad

**Comment by Harjot1Singh** [comment]
I believe we actually have this already if I'm not mistaken - `ctrl+down/up` when on the last or first line already will go to the next or previous Shabad.

**Comment by bhajneet** [comment]
@Harjot1Singh is correct, this hot key already exists. Closing resolved issue.

If you have any other questions or concerns, feel free to message us on Slack via invite at https://chat.shabados.com

**Comment by bhajneet** [comment]
Also what was the Shabad where this was required?

**Comment by bhajneet** [comment]
@readgurbani the reason I ask is because there may be an issue with the database
