### ISSUE TITLE
default mac hotkeys not working

### ISSUE THREAD

**Issue by bhajneet** [shabados/presenter#659]
**Describe the bug**
Mac users cannot use cmd+{a,c,v} in input boxes such as the search bar or zoom api box.

**Comment by saihaj** [comment]
On [`dev`](https://github.com/shabados/presenter/commit/21efae4a52faa2182eaf63467ab791502fc28634) it is working fine but when I try to run the compiled version it isn't working. (this will be fun to debug)
![Kapture 2021-07-22 at 20 01 42](https://user-images.githubusercontent.com/44710980/126723352-ae0731c7-38b5-423d-a517-d64d0ae7337a.gif)

**Comment by saihaj** [comment]
https://github.com/shabados/presenter/pull/664
