### ISSUE TITLE
Reduce DB pings

### ISSUE THREAD

**Issue by bhajneet** [shabados/presenter#663]
**Is your feature request related to a problem? Please describe.**
We do not have an accurate graph of users in npmjs. We could solve it with analytics, or a much easier solution of pinging the DB less often.

**Describe the solution you'd like**
Updating this line to 1 hour:
https://github.com/shabados/presenter/blob/ec554c0ca50a1de98661c067da9a7121478d8fe4/app/lib/consts.js#L20

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by Harjot1Singh** [comment]
On further discussion, won't do - only affects visuals.
